Added support for building programs depending on the SysLib library.

diff --git a/C/SRC/Makefile b/C/SRC/Makefile
--- a/C/SRC/Makefile
+++ b/C/SRC/Makefile
@@ -16,7 +16,7 @@
 #    2004-12-14 JFL jf.larvoire@hp.com created this file.                     #
 #    2014-12-05 JFL Finished the job. Yes, 10 years later!                    #
 #    2016-01-07 JFL Added compilation option -Wall.                           #
-#    2016-10-12 JFL Search includes in $(STINCLUDE).			      #
+#    2016-10-12 JFL Search includes in $(STINCLUDE) and $(SYSLIB).	      #
 #                                                                             #
 #         © Copyright 2016 Hewlett Packard Enterprise Development LP          #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
@@ -117,6 +117,24 @@ endif
 ifdef STINCLUDE
 CFLAGS := $(CFLAGS) -I $(STINCLUDE)
 CXXFLAGS := $(CXXFLAGS) -I $(STINCLUDE)
+endif
+
+# Add the path to SysLib library files
+ifdef SYSLIB
+  ifeq '$(shell ls -1 "$(SYSLIB)/SysLib.h" 2>/dev/null)' ''
+    $(error "Can't find the SysLib library files in $(SYSLIB)")
+  endif
+endif
+ifndef SYSLIB
+  ifneq '$(shell ls -1 "../SysLib/SysLib.h" 2>/dev/null)' ''
+    SYSLIB := ../SysLib
+  endif
+endif
+ifdef SYSLIB
+CFLAGS := $(CFLAGS) -I $(SYSLIB)
+CXXFLAGS := $(CXXFLAGS) -I $(SYSLIB)
+NLDLIBS := $(NLDLIBS) -L $(SYSLIB)/$(OSPN) -l SysLib # Normal build linker flags
+DLDLIBS := $(DLDLIBS) -L $(SYSLIB)/$(OSPD) -l SysLib # Debug build linker flags
 endif
 
 # Make file messages control
@@ -233,6 +251,10 @@ checkenv:
 	    >&2 echo "C/Makefile: Error: Can't find SysToolsLib global include files. Please export their location in STINCLUDE." ; \
 	    false ; \
 	fi
+	if [ ! -r "$(SYSLIB)/SysLib.h" ] ; then \
+	    >&2 echo "C/Makefile: Error: Can't find SysLib library files. Please export their location in SYSLIB." ; \
+	    false ; \
+	fi
 
 # How to reluild all targets
 .PHONY: all
@@ -270,6 +292,7 @@ Usage: make [MAKEOPTS] [MAKEDEFS] [TARGETS]
 
 MakeDefs:
   STINCLUDE=PATH    SysToolsLib global include dir. Default: $(STINCLUDE)
+  SYSLIB=PATH       SysLib library base dir. Default: $(SYSLIB)
 
 Targets:
   PROGRAM   Build the normal and debug versions of PROGRAM.c or .cpp
diff --git a/C/SRC/configure b/C/SRC/configure
--- a/C/SRC/configure
+++ b/C/SRC/configure
@@ -12,7 +12,7 @@
 #    2015-12-16 JFL Created this script.                                      #
 #    2016-01-06 JFL Automatically create a symbolic link to debugm.h if poss. #
 #    2016-01-08 JFL Actually copy the file instead of making a link.          #
-#    2016-10-12 JFL Search includes in $(STINCLUDE).			      #
+#    2016-10-12 JFL Search includes in $(STINCLUDE) and $(SYSLIB).	      #
 #                                                                             #
 #         © Copyright 2016 Hewlett Packard Enterprise Development LP          #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
@@ -91,5 +91,20 @@ if [ $? -ne 0 ] ; then # It's not accessible
   fi
 fi
 EchoV "OK      STINCLUDE=$STINCLUDE"
+
+EchoV "Making sure that the SysLib library is accessible"
+CPATH=$SYSLIB cc -o /dev/null -xc - >&6 2>&1 <<EOF
+#include "SysLib.h"
+int main(int argc, char *argv[]) {return 0;}
+EOF
+if [ $? -ne 0 ] ; then # It's not accessible
+  if [ -r ../SysLib/SysLib.h ] ; then
+    SYSLIB=$(pushd ../SysLib >/dev/null; pwd; popd >/dev/null)
+  else
+    >&2 echo "Error: Please set SYSLIB with the pathname of the SysLib library base directory"
+    exit 1
+  fi
+fi
+EchoV "OK      SYSLIB=$SYSLIB"
 
 echo Configuration done successfully.
