Major refactoring: Use the [NMaker](https://github.com/JFLarvoire/NMaker) subproject, instead of having a version of it built-in in the C/include directory.

diff --git a/C/SRC/Makefile b/C/SRC/Makefile
--- a/C/SRC/Makefile
+++ b/C/SRC/Makefile
@@ -34,6 +34,7 @@
 #    2021-11-08 JFL Define C macro HAS_SYSLIB when SYSLIB is present.         #
 #    2023-04-23 JFL Create the link bin -> ../bin.			      #
 #                   Fixed a failure to link with the termcap library.         #
+#    2024-01-07 JFL Define both NMINCLUDE and STINCLUDE.		      #
 #                                                                             #
 #         © Copyright 2016 Hewlett Packard Enterprise Development LP          #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
@@ -192,14 +193,30 @@ ifneq "$(CC_NOCARET_OPT)" ""
   CXXFLAGS += $(CC_NOCARET_OPT)
 endif
 
+# Add the path to NMaker include files
+ifdef NMINCLUDE
+  ifeq '$(shell ls -1 "$(NMINCLUDE)/debugm.h" 2>/dev/null)' ''
+    $(error "Can't find NMaker include files in $(NMINCLUDE)")
+  endif
+endif
+ifndef NMINCLUDE
+  ifneq '$(shell ls -1 "../include/debugm.h" 2>/dev/null)' ''
+    NMINCLUDE := ../include
+  endif
+endif
+ifdef NMINCLUDE
+CFLAGS := $(CFLAGS) -I $(NMINCLUDE)
+CXXFLAGS := $(CXXFLAGS) -I $(NMINCLUDE)
+endif
+
 # Add the path to SysToolsLib global include files
 ifdef STINCLUDE
-  ifeq '$(shell ls -1 "$(STINCLUDE)/debugm.h" 2>/dev/null)' ''
+  ifeq '$(shell ls -1 "$(STINCLUDE)/stversion.h" 2>/dev/null)' ''
     $(error "Can't find SysToolsLib global include files in $(STINCLUDE)")
   endif
 endif
 ifndef STINCLUDE
-  ifneq '$(shell ls -1 "../include/debugm.h" 2>/dev/null)' ''
+  ifneq '$(shell ls -1 "../include/stversion.h" 2>/dev/null)' ''
     STINCLUDE := ../include
   endif
 endif
@@ -360,7 +377,11 @@ check:
 # Check the build environment. Ex: global include files location
 .PHONY: checkenv
 checkenv:
-	if [ ! -r "$(STINCLUDE)/debugm.h" ] ; then \
+	if [ ! -r "$(NMINCLUDE)/debugm.h" ] ; then \
+	    >&2 echo "C/Makefile: Error: Can't find NMaker include files. Please export their location in NMINCLUDE." ; \
+	    false ; \
+	fi
+	if [ ! -r "$(STINCLUDE)/stversion.h" ] ; then \
 	    >&2 echo "C/Makefile: Error: Can't find SysToolsLib global include files. Please export their location in STINCLUDE." ; \
 	    false ; \
 	fi
@@ -423,6 +444,7 @@ Usage: make [MAKEOPTS] [MAKEDEFS] [TARGETS]
 
 MakeDefs:
   bindir=PATH       With install: Where to install files. Default: $(bindir)
+  NMINCLUDE=PATH    NMaker include directory. Default: $(NMINCLUDE)
   STINCLUDE=PATH    SysToolsLib global include dir. Default: $(STINCLUDE)
   SYSLIB=PATH       SysLib library base dir. Default: $(SYSLIB)
 
diff --git a/C/SRC/configure b/C/SRC/configure
--- a/C/SRC/configure
+++ b/C/SRC/configure
@@ -14,22 +14,33 @@
 #    2016-01-08 JFL Actually copy the file instead of making a link.          #
 #    2016-10-12 JFL Search includes in $(STINCLUDE) and $(SYSLIB).	      #
 #    2023-01-21 JFL Fixed compatibility with FreeBSD.                         #
+#    2024-01-09 JFL Define both NMINCLUDE and STINCLUDE.		      #
 #                                                                             #
 #         © Copyright 2016 Hewlett Packard Enterprise Development LP          #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
 #*****************************************************************************#
 
 # Global variables
-VERSION="2023-01-21"
+VERSION="2024-01-09"
 
 VERBOSITY=1			# Verbosity. 0=Quiet 1=Normal 2=Verbose 3=Debug
 
 # Helper routines to test verbosity levels
+Normal() {
+  [[ $VERBOSITY > 0 ]]
+}
 Verbose() {
   [[ $VERBOSITY > 1 ]]
 }
 Debug() {
   [[ $VERBOSITY > 2 ]]
+}
+
+# Display a string in normal mode
+EchoN() { # $*=echo arguments
+  if Normal ; then
+    echo "$@"
+  fi
 }
 
 # Display a string in verbose mode
@@ -48,6 +59,9 @@ case "$1" in
     echo "Prepare the environment for making SysToolsLib C tools"
     echo "Usage: ./configure [-v]"
     exit 0
+  ;;
+  -q | --quiet)
+    VERBOSITY=0
   ;;
   -v | --verbose)
     VERBOSITY=$(expr $VERBOSITY + 1)
@@ -77,14 +91,30 @@ if [ $? -ne 0 ] ; then
 fi
 EchoV "OK"
 
-# Make sure that the SysToolsLib global include directory is accessible
-EchoV "Making sure that the SysToolsLib global include directory is accessible"
-CPATH=$STINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
+# Make sure that the NMaker include directory is accessible
+EchoV "Making sure that the NMaker include directory is accessible"
+CPATH=$NMINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
 #include "debugm.h"
 int main(int argc, char *argv[]) {return 0;}
 EOF
 if [ $? -ne 0 ] ; then # It's not accessible
-  if [ -r ../include/debugm.h ] ; then
+  if [ -r ../../NMaker/include/debugm.h ] ; then
+    NMINCLUDE=$(pushd ../include >/dev/null; pwd; popd >/dev/null)
+  else
+    >&2 echo "Error: Please set NMINCLUDE with the pathname of NMaker include directory"
+    exit 1
+  fi
+fi
+EchoV "OK      NMINCLUDE=$NMINCLUDE"
+
+# Make sure that the SysToolsLib global include directory is accessible
+EchoV "Making sure that the SysToolsLib global include directory is accessible"
+CPATH=$STINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
+#include "stversion.h"
+int main(int argc, char *argv[]) {return 0;}
+EOF
+if [ $? -ne 0 ] ; then # It's not accessible
+  if [ -r ../include/stversion.h ] ; then
     STINCLUDE=$(pushd ../include >/dev/null; pwd; popd >/dev/null)
   else
     >&2 echo "Error: Please set STINCLUDE with the pathname of SysToolsLib's global include directory"
@@ -93,6 +123,7 @@ if [ $? -ne 0 ] ; then # It's not accessible
 fi
 EchoV "OK      STINCLUDE=$STINCLUDE"
 
+# Make sure that the SysLib include directory is accessible
 EchoV "Making sure that the SysLib library is accessible"
 CPATH=$SYSLIB cc -o /dev/null -xc - >&6 2>&1 <<EOF
 #include "SysLib.h"
@@ -108,4 +139,4 @@ if [ $? -ne 0 ] ; then # It's not accessible
 fi
 EchoV "OK      SYSLIB=$SYSLIB"
 
-echo Configuration done successfully.
+EchoN Configuration done successfully.
diff --git a/C/SysLib/Makefile b/C/SysLib/Makefile
--- a/C/SysLib/Makefile
+++ b/C/SysLib/Makefile
@@ -27,6 +27,7 @@
 #    2023-01-18 JFL Added a configuration step generating a config.h file.    #
 #                   Fixed a bug which cause partial builds to _not_ replace   #
 #                   the modified objects in the library.                      #
+#    2024-01-07 JFL Define both NMINCLUDE and STINCLUDE.		      #
 #                                                                             #
 #         © Copyright 2016 Hewlett Packard Enterprise Development LP          #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
@@ -191,14 +192,30 @@ endif
 CFLAGS := $(CFLAGS) -I $(IP)
 CXXFLAGS := $(CXXFLAGS) -I $(IP)
 
+# Add the path to NMaker include files
+ifdef NMINCLUDE
+  ifeq '$(shell ls -1 "$(NMINCLUDE)/debugm.h" 2>/dev/null)' ''
+    $(error "Can't find NMaker include files in $(NMINCLUDE)")
+  endif
+endif
+ifndef NMINCLUDE
+  ifneq '$(shell ls -1 "../include/debugm.h" 2>/dev/null)' ''
+    NMINCLUDE := ../include
+  endif
+endif
+ifdef NMINCLUDE
+CFLAGS := $(CFLAGS) -I $(NMINCLUDE)
+CXXFLAGS := $(CXXFLAGS) -I $(NMINCLUDE)
+endif
+
 # Add the path to SysToolsLib global include files
 ifdef STINCLUDE
-  ifeq '$(shell ls -1 "$(STINCLUDE)/debugm.h" 2>/dev/null)' ''
+  ifeq '$(shell ls -1 "$(STINCLUDE)/stversion.h" 2>/dev/null)' ''
     $(error "Can't find SysToolsLib global include files in $(STINCLUDE)")
   endif
 endif
 ifndef STINCLUDE
-  ifneq '$(shell ls -1 "../include/debugm.h" 2>/dev/null)' ''
+  ifneq '$(shell ls -1 "../include/stversion.h" 2>/dev/null)' ''
     STINCLUDE := ../include
   endif
 endif
@@ -371,8 +388,12 @@ check:
 # Check the build environment. Ex: global include files location
 .PHONY: checkenv
 checkenv:
-	if [ ! -r "$(STINCLUDE)/debugm.h" ] ; then \
-	    >&2 echo "SysLib/Makefile: Error: Can't find SysToolsLib global include files. Please export their location in STINCLUDE." ; \
+	if [ ! -r "$(NMINCLUDE)/debugm.h" ] ; then \
+	    >&2 echo "C/Makefile: Error: Can't find NMaker include files. Please export their location in NMINCLUDE." ; \
+	    false ; \
+	fi
+	if [ ! -r "$(STINCLUDE)/stversion.h" ] ; then \
+	    >&2 echo "C/Makefile: Error: Can't find SysToolsLib global include files. Please export their location in STINCLUDE." ; \
 	    false ; \
 	fi
 
@@ -425,6 +446,7 @@ Usage: make [MAKEOPTS] [MAKEDEFS] [TARGETS]
 MakeDefs:
   bindir=PATH       With install: Where to install files. Default: $(bindir)
   NOEXEC=1          With install: Show what files would be copied, but don't do it.
+  NMINCLUDE=PATH    NMaker include directory. Default: $(NMINCLUDE)
   STINCLUDE=PATH    SysToolsLib global include dir. Default: $(STINCLUDE)
 
 Targets:
diff --git a/C/SysLib/configure b/C/SysLib/configure
--- a/C/SysLib/configure
+++ b/C/SysLib/configure
@@ -9,13 +9,14 @@
 #                                                                             #
 #  History:                                                                   #
 #    2023-01-18 JFL Created this script.                                      #
+#    2024-01-09 JFL Define both NMINCLUDE and STINCLUDE.		      #
 #                                                                             #
 #                   © Copyright 2023 Jean-François Larvoire                   #
 # Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
 #*****************************************************************************#
 
 # Global variables
-VERSION="2023-01-18"
+VERSION="2024-01-09"
 
 VERBOSITY=1			# Verbosity. 0=Quiet 1=Normal 2=Verbose 3=Debug
 
@@ -85,14 +86,30 @@ if [ $? -ne 0 ] ; then
 fi
 EchoV "OK"
 
-# Make sure that the SysToolsLib global include directory is accessible
-EchoV "Making sure that the SysToolsLib global include directory is accessible"
-CPATH=$STINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
+# Make sure that the NMaker include directory is accessible
+EchoV "Making sure that the NMaker include directory is accessible"
+CPATH=$NMINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
 #include "debugm.h"
 int main(int argc, char *argv[]) {return 0;}
 EOF
 if [ $? -ne 0 ] ; then # It's not accessible
-  if [ -r ../include/debugm.h ] ; then
+  if [ -r ../../NMaker/include/debugm.h ] ; then
+    NMINCLUDE=$(pushd ../include >/dev/null; pwd; popd >/dev/null)
+  else
+    >&2 echo "Error: Please set NMINCLUDE with the pathname of NMaker include directory"
+    exit 1
+  fi
+fi
+EchoV "OK      NMINCLUDE=$NMINCLUDE"
+
+# Make sure that the SysToolsLib global include directory is accessible
+EchoV "Making sure that the SysToolsLib global include directory is accessible"
+CPATH=$STINCLUDE cc -o /dev/null -xc - >&6 2>&1 <<EOF
+#include "stversion.h"
+int main(int argc, char *argv[]) {return 0;}
+EOF
+if [ $? -ne 0 ] ; then # It's not accessible
+  if [ -r ../include/stversion.h ] ; then
     STINCLUDE=$(pushd ../include >/dev/null; pwd; popd >/dev/null)
   else
     >&2 echo "Error: Please set STINCLUDE with the pathname of SysToolsLib's global include directory"
